---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2-store
  namespace: home
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://cnpg/
    endpointURL: https://eeded8796e30bfe7b412cd59df29bb34.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: r2-cloudnative-pg
        key: aws-access-key-id
      secretAccessKey:
        name: r2-cloudnative-pg
        key: aws-secret-access-key
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
