---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-secret
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .RUSTFS_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .RUSTFS_ROOT_PASSWORD }}"
  data:
    - secretKey: RUSTFS_ROOT_USER
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_USER
    - secretKey: RUSTFS_ROOT_PASSWORD
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_PASSWORD
