---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-secret
    template:
      engineVersion: v2
      data:
        api-secret-key: "{{ .api_secret_key }}"
        oidc-client-secret: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: penpot
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-db-credentials
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-db-credentials
    template:
      engineVersion: v2
      data:
        username: "penpot"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: penpot-db
