---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-db
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-db
    template:
      data:
        username: "penpot"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: penpot-db
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-db-superuser
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: penpot-db-superuser
    template:
      data:
        username: "postgres"
        password: "{{ .superuser_password }}"
  dataFrom:
    - extract:
        key: penpot-db
        property: superuser_password
