---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-cnpg
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-cnpg
    template:
      data:
        aws-access-key-id: "{{ .MINIO_ACCESS_KEY }}"
        aws-secret-access-key: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MINIO_$1"
