---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm
resources:
  - actions-runner-controller.yaml
  - bitnami.yaml
  - bjws.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - csi-driver-nfs.yaml
  - csi-driver-smb.yaml
  - descheduler.yaml
  - dex.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - kube-vip.yaml
  - kubereboot.yaml
  - kured.yaml
  - longhorn.yaml
  - metrics-server.yaml
  - minio.yaml
  - onepassword-connect.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - ./secrets-store-csi-driver.yaml
  - ./vector.yaml
  - ./victoria-metrics.yaml
  - backube.yaml
  - zitadel.yaml
