# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: "gateway.damacus.io"
      recordType: CNAME
      targets:
        - "4cd48d19-1058-4f75-91a5-3f8619afe500.cfargotunnel.com"
    - dnsName: "hass.damacus.io"
      recordType: CNAME
      targets:
        - "4cd48d19-1058-4f75-91a5-3f8619afe500.cfargotunnel.com"
    - dnsName: "external.damacus.io"
      recordType: CNAME
      targets:
        - "4cd48d19-1058-4f75-91a5-3f8619afe500.cfargotunnel.com"
    - dnsName: "envoy-ext.damacus.io"
      recordType: CNAME
      targets:
        - "4cd48d19-1058-4f75-91a5-3f8619afe500.cfargotunnel.com"
    - dnsName: "home-assistant.damacus.io"
      recordType: CNAME
      targets:
        - "4cd48d19-1058-4f75-91a5-3f8619afe500.cfargotunnel.com"
