---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &oncall grafana-oncall-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *oncall
    template:
      engineVersion: v2
      data:
        GF_PLUGIN_GRAFANA_ONCALL_APP_ONCALL_API_URL: "https://oncall-prod-eu-west-2.grafana.net/oncall"
        GF_PLUGIN_GRAFANA_ONCALL_APP_ONCALL_TOKEN: "{{ .credential }}"
  dataFrom:
    - extract:
        key: grafana-cloud-oncall
