---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-oncall.yaml
  - ./httproute.yaml
  - ./oci-repository.yaml
  - ./helmrelease.yaml
