---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: coffee-damacus-io
  namespace: network
spec:
  endpoints:
    - dnsName: coffee.damacus.io
      recordTTL: 300
      recordType: CNAME
      targets:
        - ghs.googlehosted.com
