---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: unifi-static-records
  namespace: network
spec:
  endpoints:
    - dnsName: unas.ironstone.casa
      recordType: A
      targets:
        - "192.168.1.243"
    - dnsName: drive.ironstone.casa
      recordType: A
      targets:
        - "192.168.1.243"
    - dnsName: pikvm.ironstone.casa
      recordType: A
      targets:
        - "192.168.1.108"
