---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./kube-prometheus-stack/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./grafana/ks.yaml
  - ./loki/ks.yaml
  # - ./alloy/ks.yaml
  - ./vector/ks.yaml
  - ./victoria-metrics/ks.yaml
  # - ./mimir/ks.yaml
  # - ./unpoller/ks.yaml
