---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - cluster.yaml
  - externalsecret.yaml
  - PrometheusRules.yaml
  - minio-externalsecret.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
