---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg
    template:
      engineVersion: v2
      data:
        aws-access-key-id: "{{ .RUSTFS_ROOT_USER }}"
        aws-secret-access-key: "{{ .RUSTFS_ROOT_PASSWORD }}"
  data:
    - secretKey: RUSTFS_ROOT_USER
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_USER
    - secretKey: RUSTFS_ROOT_PASSWORD
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_PASSWORD
