---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  # - ./immich-db/ks.yaml
  - ./mealie-db/ks.yaml
  - ./mealie/ks.yaml
  - ./namespace.yaml
  - ./penpot-db/ks.yaml
  - ./penpot/ks.yaml
  # - ./trillium-next/ks.yaml
