---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-restic-local
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-restic-local
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:http://rustfs.storage.svc.cluster.local:9000/volsync-backups/home-assistant"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .RUSTFS_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .RUSTFS_ROOT_PASSWORD }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: volsync
        property: RESTIC_PASSWORD
    - secretKey: RUSTFS_ROOT_USER
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_USER
    - secretKey: RUSTFS_ROOT_PASSWORD
      remoteRef:
        key: rustfs
        property: RUSTFS_ROOT_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-restic-r2
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-restic-r2
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:https://{{ .R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/volsync/home-assistant"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: volsync
        property: RESTIC_PASSWORD
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: cloudflare-r2
        property: R2_ACCOUNT_ID
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: cloudflare-r2
        property: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: cloudflare-r2
        property: R2_SECRET_ACCESS_KEY
