---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./codeserver/ks.yaml
  - ./config-pvc.yaml
  - ./esphome/ks.yaml
  - ./externalsecret.yaml
  - ./home-assistant-db/ks.yaml
  - ./home-assistant/ks.yaml
  - ./matter/ks.yaml
  - ./mosquitto/ks.yaml
  # - ./n8n-db/ks.yaml
  # - ./n8n/ks.yaml
  - ./frigate/ks.yaml
  - ./namespace.yaml
  - ./paperless/ks.yaml
  - ./piper/ks.yaml
  - ./whisper/ks.yaml
