---
k3s_become: true
k3s_etcd_datastore: true
k3s_install_hard_links: true
k3s_registration_address: "192.168.1.220"
k3s_registries:
  mirrors:
    docker.io:
    gcr.io:
    ghcr.io:
    k8s.gcr.io:
    lscr.io:
    mcr.microsoft.com:
    public.ecr.aws:
    quay.io:
    registry.k8s.io:
# renovate: depName=k3s-io/k3s datasource=github-releases versioning=semver-coerced
k3s_release_version: v1.33.2+k3s1

# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - custom-cilium-helmchart.yaml
  - custom-kube-vip-ds.yaml
  - custom-kube-vip-rbac.yaml
k3s_use_unsupported_config: true

timezone: "Europe/London"
github_username: damacus
