---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - client-externalsecret.yaml
  - helmrelease.yaml
  - externalsecret.yaml
  - pvc.yaml
  - pvc-ssd.yaml
  - secret.yaml
  - ./volsync
