---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./dex/ks.yaml  # Removed - migrated to Zitadel
  - ./namespace.yaml
  - ./zitadel-db/ks.yaml
  - ./zitadel/ks.yaml
