---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-cnpg
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-cnpg
    template:
      engineVersion: v2
      data:
        aws-access-key-id: "{{ .RUSTFS_ACCESS_KEY }}"
        aws-secret-access-key: "{{ .RUSTFS_SECRET_KEY }}"
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: rustfs
        property: RUSTFS_ACCESS_KEY
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: rustfs
        property: RUSTFS_SECRET_KEY
