---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-masterkey
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-masterkey
    template:
      engineVersion: v2
      data:
        masterkey: "{{ .masterkey }}"
  dataFrom:
    - extract:
        key: zitadel
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-credentials
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-credentials
    template:
      engineVersion: v2
      data:
        config-yaml: |
          Database:
            Postgres:
              Host: zitadel-rw.authentication.svc.cluster.local
              Port: 5432
              Database: zitadel
              User:
                Username: zitadel
                Password: "{{ .DB_password }}"
                SSL:
                  Mode: disable
              Admin:
                Username: postgres
                Password: "{{ .SUPERUSER_password }}"
                SSL:
                  Mode: disable
          FirstInstance:
            Org:
              Human:
                UserName: "{{ .admin_username }}"
                FirstName: Admin
                LastName: User
                Email:
                  Address: "{{ .admin_email }}"
                  Verified: true
                Password: "{{ .admin_password }}"
                PasswordChangeRequired: false
  dataFrom:
    - extract:
        key: zitadel
    - extract:
        key: zitadel-db
      rewrite:
        - regexp:
            source: "(.*)"
            target: "DB_$1"
    - extract:
        key: zitadel-db-superuser
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SUPERUSER_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-google-idp
  namespace: authentication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zitadel-google-idp
    template:
      engineVersion: v2
      data:
        client-id: "{{ .GOOGLE_CLIENT_ID }}"
        client-secret: "{{ .GOOGLE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: dex-google
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GOOGLE_$1"
