---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./webhooks/ks.yaml
  - ./flux-operator/ks.yaml
  # TODO: Enable flux-instance after consolidating receivers and secrets
  # - ./flux-instance/ks.yaml
