---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-restic-local
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-restic-local
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:http://minio.storage.svc.cluster.local:9000/volsync-backups/paperless"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .username }}"
        AWS_SECRET_ACCESS_KEY: "{{ .password }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: volsync
        property: RESTIC_PASSWORD
    - secretKey: username
      remoteRef:
        key: minio
        property: username
    - secretKey: password
      remoteRef:
        key: minio
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-restic-r2
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-restic-r2
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:https://{{ .R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/volsync/paperless"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: volsync
        property: RESTIC_PASSWORD
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: cloudflare-r2
        property: R2_ACCOUNT_ID
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: cloudflare-r2
        property: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: cloudflare-r2
        property: R2_SECRET_ACCESS_KEY
