---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.11@sha256:44ae136890c37438f5324e4fe5b1f79e556440585688fe558604cc0d408bc560
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.6
