---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.11@sha256:f0b8e5538b1766134bfe32499a9ac7bbbf893d5d0ba21d65e81046b13c7830aa
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.6
