---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.11@sha256:63f938b0d63559b129da7a4b7aa870a5354e37521038d37643db2800652ae65e
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.6
