---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-traefik-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-int.ironstone.casa"
spec:
  hostnames:
    - hass.ironstone.casa
    - home-assistant.ironstone.casa
  parentRefs:
    - name: traefik-internal
      namespace: network
      sectionName: websecure
  rules:
    - backendRefs:
        - kind: Service
          name: home-assistant
          port: 8123
      matches:
        - path:
            type: PathPrefix
            value: /
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-traefik-external
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-ext.damacus.io"
spec:
  hostnames:
    - hass.damacus.io
    - home-assistant.damacus.io
  parentRefs:
    - name: traefik-internal
      namespace: network
      sectionName: websecure
  rules:
    - backendRefs:
        - kind: Service
          name: home-assistant
          port: 8123
      matches:
        - path:
            type: PathPrefix
            value: /
